### ISSUE TITLE
Custom color schemes 

### ISSUE THREAD

**Issue by alekbless** [nagix/chartjs-plugin-colorschemes#15]
Should it be possible to let users define their own complete schemes? Or is the custom-Function the way to go for this?

**Comment by danmana** [comment]
It is possible to specify a complete theme without using the custom function.
Just place your own colors array instead of the scheme name, like so:

```
options: {
        plugins: {
            colorschemes: {
                scheme: ['red', 'green', 'blue', 'orange', 'black', 'yellow']
            }
        }
    }
```
