### ISSUE TITLE
Scatter Chart Colors

### ISSUE THREAD

**Issue by xyrph** [nagix/chartjs-plugin-colorschemes#2]
Nice plugin. It seems to work well for the POINTS on my scatter charts, but the lines between the points are left as the default gray color that comes with chartjs.

How can I fix this problem?

**Comment by xyrph** [comment]
I fixed this by adding 'scatter' to your switch() statement. You just forgot to include the 'scatter' chart type.

**Comment by nagix** [comment]
Thank you for reporting the issue. 4d3aaa2 fixed this.
