### ISSUE TITLE
Maintained alternative?

### ISSUE THREAD

**Issue by sabatale** [nagix/chartjs-plugin-colorschemes#20]
Does anyone know whether there is a "maintained" alternative to this repository?

(great job, by the way!)

**Comment by nagix** [comment]
Closing as I'm now preparing v1.0.0 with Chart.js v3 support.

**Comment by homestar9** [comment]
@sabatale, check out https://www.npmjs.com/package/chartjs-plugin-colorschemes-v3

I'm not sure if @nagix still maintains this repo, and I had luck with the above package and ChartJS version 3.  It does not work on Version 4 though.
