### ISSUE TITLE
Plugin doesn't work with Chart.js 3.x.x

### ISSUE THREAD

**Issue by esttenorio** [nagix/chartjs-plugin-colorschemes#25]
Please add support for Chartjs 3.x.x or at least mention it in the README since it only says "This plugin requires Chart.js 2.5.0 or later."

Chart.js changed from `Chart.defaults.global` to `Chart.defaults` in the new version. 

![image](https://user-images.githubusercontent.com/8483207/110569302-32afc180-8109-11eb-8041-982836d44538.png)
![image](https://user-images.githubusercontent.com/8483207/110569338-3d6a5680-8109-11eb-96e3-bd72573189f3.png)

https://www.chartjs.org/docs/master/getting-started/v3-migration/#defaults

**Comment by MartijnVerkleij** [comment]
Hi there, I implemented some changes in #26 that may help you in the meantime.
