### ISSUE TITLE
Color returns to gray after hover on pie chart

### ISSUE THREAD

**Issue by bestrong89** [nagix/chartjs-plugin-colorschemes#5]
Hello,

On a pie chart, after you hover on the pie section, the color returns to gray.

![screen shot 2019-01-14 at 5 15 46 pm](https://user-images.githubusercontent.com/12430891/51147523-1dd48d80-1820-11e9-8f31-b7084fd1af76.png)

![screen shot 2019-01-14 at 5 15 58 pm](https://user-images.githubusercontent.com/12430891/51147511-1a410680-1820-11e9-8029-7bfb4e268e75.png)

**Comment by nagix** [comment]
Thank you for reporting this issue. This doesn’t happens with Chart.js 2.7.3, but I will look for the solution with older versions.

**Comment by nagix** [comment]
This issue was fixed in 2c8103b.

**Comment by nagix** [comment]
Closing as v0.3.0 was just released.
