### ISSUE TITLE
colorschemes not working  

### ISSUE THREAD

**Issue by mohamedmohsin** [nagix/chartjs-plugin-colorschemes#9]
@nagix 
this is my option in data 
options:{
	plugins : {
		colorschemes : {
			scheme : 'brewer.YlGn3'
		}
	}
}

by default brewer.Paired12 is applied even  I change other schemes

**Comment by nagix** [comment]
Can you share entire js code, or more preferably, a working sample using jsfiddle, codepen or similar?

**Comment by mohamedmohsin** [comment]
Thanks for response @nagix  , now working fine .Previously I gave the options inside data that is reason the color scheme was not changed
